config/routes.rb
HackerNewsCloneWeb::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  

  resources :sessions
  resources :users

  resources :links, :votes

  resources :links do 
    resources :votes
  end

  root :to => 'links#index'

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :url, :description
  validates :url, format: {with: /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix}
  validates :url, :description, :presence => true
  has_many :votes

  def count_votes
    votes.inject(0) {|sum, vote| sum += vote.up_down}
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :password, :password_confirmation 

  validates_uniqueness_of :email
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :up_down, :link_id
  belongs_to :link
  validates :up_down, :link_id, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end


  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def new
    @link = Link.new
  end

  def create
    @link = Link.new(params[:link])

    if @link.save
      flash[:notice] = 'Your link was successfully created.'
      redirect_to links_path
    else
      render :new
      flash[:alert] = 'That is an invalid link. Please try again.'
    end

  end

  def index
    @links = Link.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      redirect_to new_session_path, alert: "Email or password is invalid." 
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, alert: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      redirect_to signup_path, alert: "Invalid email or password"
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_filter :authorize, only: [:new, :create]

  def new
    @vote = Vote.new
  end

  def create
    @vote = Link.find(params[:link_id]).votes.create(params[:vote])

    if @vote.save
      flash[:notice] = 'Thanks for voting.'
      redirect_to links_path
    end
  end

  def index
    @votes = Vote.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <div class="container">
    <div id="user_header">
      <% if current_user %>
        Logged in as <%= current_user.email %>.
        <%= link_to "Log Out", logout_path, method: "delete" %>
      <% else %>
        <%= link_to "Sign Up", signup_path, :class => 'btn btn-primary btn-small' %>
        <%= link_to "Log In", login_path, :class => 'btn btn-success btn-small' %>
      <% end %>
    </div>
  </div>
  <title>Hacker News Clone | <%= yield :title %></title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
 <body>

  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-info"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-error"><%= flash[:alert] %></div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/links/_form.html.erb
<% if @link.errors.any? %>
  <div class="alert alert-error">
    <h3>Please correct these problems.</h3>
    <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @link do |f| %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit :class => 'btn btn-primary' %>
<% end %>

app/views/links/index.html.erb
<% provide :title, "Hacker News Clone" %>



<h1><%= yield :title %></h1>

<h2>A user-contributed news discovery site.</h2>

<table class="table">
  <tr>
    <td>URL</td>
    <td>Description</td>
    <td>Vote Up</td>
    <td>Vote Down</td>
    <td>Total</td>
    
  </tr>
  <% @links.each do |link| %>
    <tr>
      <td><%= link_to link.url, "#{link.url}"  %></td>
      <td><%= link.description  %></td>
      <td><%= link_to 'Vote Up', link_votes_path(link, :vote => {:up_down => 1}), :method => :post, :class => 'btn btn-primary' %></td>
      <td><%= link_to 'Vote Down', link_votes_path(link, :vote => {:up_down => -1}), :method => :post, :class => 'btn btn-primary' %></td>
      <td><%= link.count_votes %></td>
   </tr>
  <% end %>
</table>

<p><%= link_to 'Add link', new_link_path, :class => 'btn btn-primary' %></p>

app/views/links/new.html.erb
<% provide :title, "New Link" %>

<h1><%= yield :title %></h1>

<!-- <h1>New link</h1> -->

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>